name: benchmarks

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]

env:
  MAINNET_EXECUTION_RPC: ${{ secrets.MAINNET_EXECUTION_RPC }}
  SEPOLIA_EXECUTION_RPC: ${{ secrets.SEPOLIA_EXECUTION_RPC }}

jobs:
  benches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af  # v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32  # v2.9.1
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505  # v1
        with:
          command: bench --package helios
